"""Version information."""
__title__ = "fbm"
__description__ = "Fractional Brownian motion realizations."
__url__ = "https://github.com/crflynn/fbm"
__version__ = "0.2.0"
__author__ = "Christopher Flynn"
__author_email__ = "crf204@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2017-2018 Christopher Flynn"
__docs_copyright__ = "2017-2018 Christopher Flynn"
